Map:
    min-location:
    max-location:
    blocks:
       - oak_planks
    candy-basket-amount: 4
candy-basket-id:
       - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGQzMTE3M2U3YjdjNzhlNWU0OGRjZmY2NmQ1Nzk4MGFlY2EzODI0Y2Q4NTg0YWFjNDZkNzdjMjYwYzM4YmI0YyJ9fX0
       - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmM0MmI5NWVlMWE3OGIwOGI4ZjllN2FjZmVkZjMzYWQ2ZTRlY2QwODE5MTI1MThiYTk5ZjA0MWE3ZWYyMWYxYiJ9fX0
       - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzk2Njg3NjdmMTE0MTgzNWUyYzQ5YWQyYjQxNTU5OGYxYjE2NmJlOTE3MzkwMmEwMjU3ZTc3NzA0ZjkxM2UxZiJ9fX0
       - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjY3MGMzN2EyZjE3N2U4YWZlMjk2MjdhZGZiNjkyYmFiMzBiYTY3OTczNmNjY2NjODI2MTQ4OTg3ZjliY2YyNyJ9fX0
       - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGViNDZiYmNhMzgxMjM2M2I1OTY3NmZmNjI5ZGMzNjk4MjU3ZmQxNzhkMzk0ZmFkZmZkYTcxNDM0MjJlMmYxMCJ9fX0