name: HalloweenSimulator
main: com.thomasandrasek.hallosim.Main
version: 1.0
author: Thomas Andrasek
description: Happy Halloween!
api-version: 1.16
commands:
    hello:
        description: Test hello command.
        usage: /hello
        permission: HalloweenSimulator.hello
        permission-message: You don't have <permission>
    hs-wand:
        description: Gives player map wand.
        usage: /hs-wand
        permission: HalloweenSimulator.hs-wand
        permission-message: You don't have <permission>
    hs-set-map:
        description: Sets the minimum and maximum location of the map.
        usage: /hs-set-map
        permission: HalloweenSimulator.hs-set-map
        permission-message: You don't have <permission>